image: maven:3.8-openjdk-11

default:
  tags:
    - shelllocal

stages:
  - tests
  - allure


UI tests with Allure:
  stage: tests
  allow_failure: true
  script:
    - mvn clean test
  artifacts:
    when: always
    paths:
      - target/allure-results

Allure report:
  stage: allure
  script:
    - mvn allure:report
  artifacts:
    when: always
    paths:
      - target/site/allure-maven-plugin/*
